server:
  port: 8082

spring:
  application:
    name: MessengerService
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/social-network
  flyway:
    enabled: true
    schemas:
      - public
    locations:
      - classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://postgres-messenger:5432/messenger_db
    username: admin
    password: admin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  host: ${spring.rabbitmq.host}
  stomp:
    port: 61613
  user: ${spring.rabbitmq.username}
  password: ${spring.rabbitmq.password}
  exchange:
    name: chat.exchange