spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  flyway:
    enabled: true
    schemas: public
    clean-disabled: false
    locations:
      - classpath:db/migration
      - classpath:db/testdata

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.flywaydb.core: DEBUG