server:
  port: 8081

spring:
  application:
    name: PersonalCabinetService

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/social-network

  flyway:
    enabled: true
    schemas:
      - public
    locations:
      - classpath:db/migration
      - classpath:db/testdata

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5434/personal-cabinet-db
    username: admin
    password: admin

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: user-avatars
